# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QMainWindow, QPushButton, QRadioButton, QSizePolicy,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1020, 863)
        MainWindow.setMinimumSize(QSize(1020, 863))
        MainWindow.setMaximumSize(QSize(1020, 863))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.menu_frame = QFrame(self.centralwidget)
        self.menu_frame.setObjectName(u"menu_frame")
        self.menu_frame.setGeometry(QRect(0, 0, 1020, 353))
        self.menu_frame.setFrameShape(QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QFrame.Raised)
        self.Menu_label = QLabel(self.menu_frame)
        self.Menu_label.setObjectName(u"Menu_label")
        self.Menu_label.setGeometry(QRect(0, 10, 1020, 31))
        font = QFont()
        font.setFamilies([u"Dyuthi"])
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.Menu_label.setFont(font)
        self.Menu_label.setLayoutDirection(Qt.LeftToRight)
        self.Menu_label.setAutoFillBackground(False)
        self.Menu_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.Menu_label.setLineWidth(2)
        self.Menu_label.setTextFormat(Qt.AutoText)
        self.Menu_label.setScaledContents(False)
        self.Menu_label.setAlignment(Qt.AlignCenter)
        self.Menu_label.setWordWrap(False)
        self.transformarFrame = QFrame(self.menu_frame)
        self.transformarFrame.setObjectName(u"transformarFrame")
        self.transformarFrame.setGeometry(QRect(510, 50, 340, 303))
        self.transformarFrame.setFrameShape(QFrame.StyledPanel)
        self.transformarFrame.setFrameShadow(QFrame.Raised)
        self.R_label = QLabel(self.transformarFrame)
        self.R_label.setObjectName(u"R_label")
        self.R_label.setGeometry(QRect(100, 10, 131, 21))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(True)
        font1.setUnderline(False)
        self.R_label.setFont(font1)
        self.R_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.getRX = QLineEdit(self.transformarFrame)
        self.getRX.setObjectName(u"getRX")
        self.getRX.setGeometry(QRect(55, 60, 50, 25))
        self.getRX.setAlignment(Qt.AlignCenter)
        self.RX_label = QLabel(self.transformarFrame)
        self.RX_label.setObjectName(u"RX_label")
        self.RX_label.setGeometry(QRect(65, 40, 30, 17))
        font2 = QFont()
        font2.setBold(True)
        self.RX_label.setFont(font2)
        self.RX_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.RX_label.setAlignment(Qt.AlignCenter)
        self.RY_label = QLabel(self.transformarFrame)
        self.RY_label.setObjectName(u"RY_label")
        self.RY_label.setGeometry(QRect(155, 40, 30, 17))
        self.RY_label.setFont(font2)
        self.RY_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.RY_label.setAlignment(Qt.AlignCenter)
        self.getRY = QLineEdit(self.transformarFrame)
        self.getRY.setObjectName(u"getRY")
        self.getRY.setGeometry(QRect(145, 60, 50, 25))
        self.getRY.setAlignment(Qt.AlignCenter)
        self.RZ_label = QLabel(self.transformarFrame)
        self.RZ_label.setObjectName(u"RZ_label")
        self.RZ_label.setGeometry(QRect(245, 40, 30, 17))
        self.RZ_label.setFont(font2)
        self.RZ_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.RZ_label.setAlignment(Qt.AlignCenter)
        self.getRZ = QLineEdit(self.transformarFrame)
        self.getRZ.setObjectName(u"getRZ")
        self.getRZ.setGeometry(QRect(235, 60, 50, 25))
        self.getRZ.setAlignment(Qt.AlignCenter)
        self.getTX = QLineEdit(self.transformarFrame)
        self.getTX.setObjectName(u"getTX")
        self.getTX.setGeometry(QRect(55, 160, 50, 25))
        self.getTX.setAlignment(Qt.AlignCenter)
        self.getTX.setClearButtonEnabled(False)
        self.T_label = QLabel(self.transformarFrame)
        self.T_label.setObjectName(u"T_label")
        self.T_label.setGeometry(QRect(100, 110, 160, 21))
        self.T_label.setFont(font1)
        self.T_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.TZ_label = QLabel(self.transformarFrame)
        self.TZ_label.setObjectName(u"TZ_label")
        self.TZ_label.setGeometry(QRect(245, 140, 30, 17))
        self.TZ_label.setFont(font2)
        self.TZ_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.TZ_label.setAlignment(Qt.AlignCenter)
        self.getTZ = QLineEdit(self.transformarFrame)
        self.getTZ.setObjectName(u"getTZ")
        self.getTZ.setGeometry(QRect(235, 160, 50, 25))
        self.getTZ.setAlignment(Qt.AlignCenter)
        self.getTY = QLineEdit(self.transformarFrame)
        self.getTY.setObjectName(u"getTY")
        self.getTY.setGeometry(QRect(145, 160, 50, 25))
        self.getTY.setAlignment(Qt.AlignCenter)
        self.TY_label = QLabel(self.transformarFrame)
        self.TY_label.setObjectName(u"TY_label")
        self.TY_label.setGeometry(QRect(155, 140, 30, 17))
        self.TY_label.setFont(font2)
        self.TY_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.TY_label.setAlignment(Qt.AlignCenter)
        self.TX_label = QLabel(self.transformarFrame)
        self.TX_label.setObjectName(u"TX_label")
        self.TX_label.setGeometry(QRect(65, 140, 30, 17))
        self.TX_label.setFont(font2)
        self.TX_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.TX_label.setAlignment(Qt.AlignCenter)
        self.Ref_label = QLabel(self.transformarFrame)
        self.Ref_label.setObjectName(u"Ref_label")
        self.Ref_label.setGeometry(QRect(100, 210, 130, 20))
        self.Ref_label.setFont(font1)
        self.Ref_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.refWORLD = QRadioButton(self.transformarFrame)
        self.refWORLD.setObjectName(u"refWORLD")
        self.refWORLD.setGeometry(QRect(55, 240, 80, 20))
        font3 = QFont()
        font3.setPointSize(12)
        font3.setBold(True)
        self.refWORLD.setFont(font3)
        self.refWORLD.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.refWORLD.setChecked(True)
        self.refWORLD.setAutoRepeat(False)
        self.refCAM = QRadioButton(self.transformarFrame)
        self.refCAM.setObjectName(u"refCAM")
        self.refCAM.setGeometry(QRect(195, 240, 80, 20))
        self.refCAM.setFont(font3)
        self.refCAM.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.transformar = QPushButton(self.transformarFrame)
        self.transformar.setObjectName(u"transformar")
        self.transformar.setGeometry(QRect(185, 270, 110, 25))
        self.transformar.setFont(font3)
        self.resetTransformar = QPushButton(self.transformarFrame)
        self.resetTransformar.setObjectName(u"resetTransformar")
        self.resetTransformar.setGeometry(QRect(35, 270, 110, 25))
        self.resetTransformar.setFont(font3)
        self.optionsFrame = QFrame(self.menu_frame)
        self.optionsFrame.setObjectName(u"optionsFrame")
        self.optionsFrame.setGeometry(QRect(170, 50, 340, 303))
        self.optionsFrame.setFrameShape(QFrame.StyledPanel)
        self.optionsFrame.setFrameShadow(QFrame.Raised)
        self.optionLabel = QLabel(self.optionsFrame)
        self.optionLabel.setObjectName(u"optionLabel")
        self.optionLabel.setGeometry(QRect(75, 10, 195, 21))
        self.optionLabel.setFont(font1)
        self.optionLabel.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.getDFocal = QLineEdit(self.optionsFrame)
        self.getDFocal.setObjectName(u"getDFocal")
        self.getDFocal.setGeometry(QRect(145, 80, 50, 25))
        self.getDFocal.setAlignment(Qt.AlignCenter)
        self.dFocal_label = QLabel(self.optionsFrame)
        self.dFocal_label.setObjectName(u"dFocal_label")
        self.dFocal_label.setGeometry(QRect(75, 50, 190, 21))
        self.dFocal_label.setFont(font1)
        self.dFocal_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.resetOptions = QPushButton(self.optionsFrame)
        self.resetOptions.setObjectName(u"resetOptions")
        self.resetOptions.setGeometry(QRect(40, 270, 110, 25))
        self.resetOptions.setFont(font3)
        self.alterarOptions = QPushButton(self.optionsFrame)
        self.alterarOptions.setObjectName(u"alterarOptions")
        self.alterarOptions.setGeometry(QRect(190, 270, 110, 25))
        self.alterarOptions.setFont(font3)
        self.tCCD_label = QLabel(self.optionsFrame)
        self.tCCD_label.setObjectName(u"tCCD_label")
        self.tCCD_label.setGeometry(QRect(75, 120, 190, 21))
        self.tCCD_label.setFont(font1)
        self.tCCD_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.tCCD_label.setAlignment(Qt.AlignCenter)
        self.getCCD_X = QLineEdit(self.optionsFrame)
        self.getCCD_X.setObjectName(u"getCCD_X")
        self.getCCD_X.setGeometry(QRect(100, 150, 50, 25))
        self.getCCD_X.setAlignment(Qt.AlignCenter)
        self.getCCD_Y = QLineEdit(self.optionsFrame)
        self.getCCD_Y.setObjectName(u"getCCD_Y")
        self.getCCD_Y.setGeometry(QRect(190, 150, 50, 25))
        self.getCCD_Y.setAlignment(Qt.AlignCenter)
        self.getIMG_Y = QLineEdit(self.optionsFrame)
        self.getIMG_Y.setObjectName(u"getIMG_Y")
        self.getIMG_Y.setGeometry(QRect(190, 220, 50, 25))
        self.getIMG_Y.setAlignment(Qt.AlignCenter)
        self.getIMG_X = QLineEdit(self.optionsFrame)
        self.getIMG_X.setObjectName(u"getIMG_X")
        self.getIMG_X.setGeometry(QRect(100, 220, 50, 25))
        self.getIMG_X.setAlignment(Qt.AlignCenter)
        self.tIMG_label = QLabel(self.optionsFrame)
        self.tIMG_label.setObjectName(u"tIMG_label")
        self.tIMG_label.setGeometry(QRect(55, 190, 230, 21))
        self.tIMG_label.setFont(font1)
        self.tIMG_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.tIMG_label.setAlignment(Qt.AlignCenter)
        self._3D_frame = QFrame(self.centralwidget)
        self._3D_frame.setObjectName(u"_3D_frame")
        self._3D_frame.setGeometry(QRect(0, 355, 510, 510))
        self._3D_frame.setFrameShape(QFrame.StyledPanel)
        self._3D_frame.setFrameShadow(QFrame.Raised)
        self._2D_frame = QFrame(self.centralwidget)
        self._2D_frame.setObjectName(u"_2D_frame")
        self._2D_frame.setGeometry(QRect(510, 355, 510, 510))
        self._2D_frame.setFrameShape(QFrame.StyledPanel)
        self._2D_frame.setFrameShadow(QFrame.Raised)
        MainWindow.setCentralWidget(self.centralwidget)
        QWidget.setTabOrder(self.getDFocal, self.getCCD_X)
        QWidget.setTabOrder(self.getCCD_X, self.getCCD_Y)
        QWidget.setTabOrder(self.getCCD_Y, self.getIMG_X)
        QWidget.setTabOrder(self.getIMG_X, self.getIMG_Y)
        QWidget.setTabOrder(self.getIMG_Y, self.getRX)
        QWidget.setTabOrder(self.getRX, self.getRY)
        QWidget.setTabOrder(self.getRY, self.getRZ)
        QWidget.setTabOrder(self.getRZ, self.getTX)
        QWidget.setTabOrder(self.getTX, self.getTY)
        QWidget.setTabOrder(self.getTY, self.getTZ)
        QWidget.setTabOrder(self.getTZ, self.refWORLD)
        QWidget.setTabOrder(self.refWORLD, self.refCAM)
        QWidget.setTabOrder(self.refCAM, self.resetOptions)
        QWidget.setTabOrder(self.resetOptions, self.alterarOptions)
        QWidget.setTabOrder(self.alterarOptions, self.resetTransformar)
        QWidget.setTabOrder(self.resetTransformar, self.transformar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Vis\u00e3o Computacional - Trab 01", None))
        self.Menu_label.setText(QCoreApplication.translate("MainWindow", u"MENU", None))
        self.R_label.setText(QCoreApplication.translate("MainWindow", u"ROTACIONAR", None))
        self.RX_label.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.RY_label.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.RZ_label.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.T_label.setText(QCoreApplication.translate("MainWindow", u"TRANSLADAR [\u00ba]", None))
        self.TZ_label.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.TY_label.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.TX_label.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.Ref_label.setText(QCoreApplication.translate("MainWindow", u"REFERENCIAL", None))
        self.refWORLD.setText(QCoreApplication.translate("MainWindow", u"Mundo", None))
        self.refCAM.setText(QCoreApplication.translate("MainWindow", u"C\u00e2mera", None))
        self.transformar.setText(QCoreApplication.translate("MainWindow", u"Transformar", None))
        self.resetTransformar.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.optionLabel.setText(QCoreApplication.translate("MainWindow", u"OP\u00c7\u00d5ES DE C\u00c2MERA", None))
        self.dFocal_label.setText(QCoreApplication.translate("MainWindow", u"Dist\u00e2ncia Focal [mm]", None))
        self.resetOptions.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.alterarOptions.setText(QCoreApplication.translate("MainWindow", u"Alterar", None))
        self.tCCD_label.setText(QCoreApplication.translate("MainWindow", u"Tamanho CCD [mm]", None))
        self.tIMG_label.setText(QCoreApplication.translate("MainWindow", u"Tamanho Imagem [pixels]", None))
    # retranslateUi

